schema:
  - ../server/schema.graphql
  - http://localhost:8000/graphql/

documents:
  - src/**/*.tsx
#   - src/**/*.graphql

generates:
  ./src/gql/:
    preset: "client"
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
