# https://docs.docker.com/reference/compose-file/version-and-name/
name: ci-and-cd-demo

# https://docs.docker.com/reference/compose-file/services/
services:
  actions-runner:
    # https://docs.docker.com/reference/compose-file/services/#build
    build:
      # https://docs.docker.com/reference/compose-file/build/#context
      context: ./actions-runner
      # https://docs.docker.com/reference/compose-file/build/#args
      args:
        RUNNER_VERSION: ${RUNNER_VERSION}
    # https://docs.docker.com/reference/compose-file/services/#tty
    tty: true
    # https://docs.docker.com/reference/compose-file/services/#stdin_open
    stdin_open: true
    # https://docs.docker.com/reference/compose-file/services/#volumes
    volumes:
      - actions-runner-data:/actions-runner
      - /var/run/docker.sock:/var/run/docker.sock
    # https://docs.docker.com/reference/compose-file/services/#environment
    environment:
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME:-ci-and-cd-demo-runner}
      - RUNNER_LABELS=${RUNNER_LABELS:-ci-and-cd-demo-runner}

  jenkins:
    build:
      context: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  nexus:
    # https://docs.docker.com/reference/compose-file/services/#image
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

  deploy:
    build:
      context: ./deploy
      args:
        - NEXUS_HOST=${NEXUS_HOST:-http://nexus:8081}
        - NEXUS_PASSWORD=${NEXUS_PASSWORD}
        - NEXUS_USER=${NEXUS_USER:-admin}
        - NEXUS_REPO=${NEXUS_REPO}
    tty: true
    stdin_open: true
    ports:
      - 80:80
      - 443:443
    volumes:
      # NOTE: SSH 설정 등 유지 한다
      - deploy_data:/home/appuser
      # NOTE: 최초 한번만 배포 서버에 직접 파일을 업로드하고 이후는 해당 스크립트를 통해 업데이트 된다
      - deploy_from_nexus.sh:/app/deploy_from_nexus.sh

# https://docs.docker.com/reference/compose-file/volumes/
volumes:
  # NOTE: Actions Runner 작업 경로를 최상위 볼륨으로 설정하기
  # - Runner 의 config.sh 실행 후, 생성 된 파일 보존을 위해
  # - Runner 의 Token 유지를 위해
  actions-runner-data:
  nexus-data:
  jenkins_data:
  deploy_data:
