# https://docs.docker.com/reference/compose-file/version-and-name/
name: ci-and-cd-demo

# https://docs.docker.com/reference/compose-file/services/
services:
  actions-runner:
    # https://docs.docker.com/reference/compose-file/services/#build
    build:
      # https://docs.docker.com/reference/compose-file/build/#context
      context: ./actions-runner
      # https://docs.docker.com/reference/compose-file/build/#args
      args:
        RUNNER_VERSION: ${RUNNER_VERSION}
    # https://docs.docker.com/reference/compose-file/services/#tty
    tty: true
    # https://docs.docker.com/reference/compose-file/services/#stdin_open
    stdin_open: true
    # https://docs.docker.com/reference/compose-file/services/#volumes
    volumes:
      - actions-runner-data:/actions-runner
      - /var/run/docker.sock:/var/run/docker.sock
    # https://docs.docker.com/reference/compose-file/services/#environment
    environment:
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME:-ci-and-cd-demo-runner}
      - RUNNER_LABELS=${RUNNER_LABELS:-ci-and-cd-demo-runner}

  jenkins:
    build:
      context: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  server:
    build:
      context: ./server
    ports:
      - 8000:8000
    # https://docs.docker.com/reference/compose-file/services/#depends_on
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}

  nexus:
    # https://docs.docker.com/reference/compose-file/services/#image
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

  db:
    build:
      context: ./db
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS:-"--encoding=UTF8 --lc-collate=ko_KR.utf8 --lc-ctype=ko_KR.utf8"}

# https://docs.docker.com/reference/compose-file/volumes/
volumes:
  # NOTE: Actions Runner 작업 경로를 최상위 볼륨으로 설정하기
  # - Runner 의 config.sh 실행 후, 생성 된 파일 보존을 위해
  # - Runner 의 Token 유지를 위해
  actions-runner-data:
  nexus-data:
  jenkins_data:
  db-data:
