# https://docs.docker.com/reference/compose-file/version-and-name/
name: ci-and-cd-demo

# https://docs.docker.com/reference/compose-file/services/
services:
  client:
    # https://docs.docker.com/reference/compose-file/services/#build
    build:
      context: ./client
      dockerfile: Dockerfile
    # https://docs.docker.com/reference/compose-file/services/#ports
    ports:
      - 4173:4173
    # https://docs.docker.com/reference/compose-file/services/#tty
    tty: true
    # https://docs.docker.com/reference/compose-file/services/#stdin_open
    stdin_open: true
    # https://docs.docker.com/reference/compose-file/services/#restart
    restart: unless-stopped

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    # https://docs.docker.com/reference/compose-file/services/#volumes
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped

  nexus:
    # https://docs.docker.com/reference/compose-file/services/#image
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

# https://docs.docker.com/reference/compose-file/volumes/
volumes:
  nexus-data:
  jenkins_data:
