[project]
name = "ci-and-cd-damo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
