name: ci-and-cd-demo-ci
on:
  push:
    branches: [main]

jobs:
  client-build:
    runs-on: [ci-and-cd-demo-runner]
    steps:
      - uses: actions/checkout@v4
      - name: Build client
        working-directory: client
        run: |
          source $NVM_DIR/nvm.sh
          yarn --version
          yarn install --immutable
          yarn run build
      - name: Archive client dist
        run: tar -cvf client/dist.tar -C client/dist .
      - name: Upload client artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist.tar
